version: '3'

services:
  redis-master:
    image: redis:7.4-rc
    command: redis-server --requirepass password
    ports:
      - "6379:6379"
    volumes:
      - ./data:/data

  redis-slave-1:
    image: redis:7.4-rc
    command: redis-server --slaveof redis-master 6379 --requirepass password
    volumes:
      - ./data:/data

  redis-slave-2:
    image: redis:7.4-rc
    command: redis-server --slaveof redis-master 6379 --requirepass password
    volumes:
      - ./data:/data

  redis-sentinel-1:
    image: redis:7.4-rc
    command: redis-sentinel /usr/local/etc/redis/sentinel.conf
    ports:
      - "26379:26379"
    volumes:
      - ./sentinel.conf:/usr/local/etc/redis/sentinel.conf
    depends_on:
      - redis-master
      - redis-slave-1
      - redis-slave-2

  redis-sentinel-2:
    image: redis:7.4-rc
    command: redis-sentinel /usr/local/etc/redis/sentinel.conf
    ports:
      - "26380:26379"
    volumes:
      - ./sentinel.conf:/usr/local/etc/redis/sentinel.conf
    depends_on:
      - redis-master
      - redis-slave-1
      - redis-slave-2

  redis-sentinel-3:
    image: redis:7.4-rc
    command: redis-sentinel /usr/local/etc/redis/sentinel.conf
    ports:
      - "26381:26379"
    volumes:
      - ./sentinel.conf:/usr/local/etc/redis/sentinel.conf
    depends_on:
      - redis-master
      - redis-slave-1
      - redis-slave-2
